id: P4AC61614
initial_creation_type: input
source_metadata:
  title: Yangthang Rinpoche Series
  language: zh
  description: Texts by Domang Yangthang Rinpoche (mdo mang g.yang thang rin po che,
    1929–2016), the renowned incarnation of Domang Dorje Dechen Lingpa (1857–1928).
  volume:
    3f60c7199228428f89217fc034b52cf5:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    e020062d91ea437d9b83693d56e4e4e4:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers
created_at: '2022-03-01T02:01:26.942710'
last_modified_at: '2022-03-01T02:01:26.942712'
